### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by glandium** [lamby/trydiffoscope#17]
When the files are too big (not sure what the cut-off point is, but 50MB is too big), try.diffoscope.org fails with a 413 Request Entity Too Large error.

**Comment by lamby** [comment]
Thanks. Have bumped to 50MB as well as exposed that "limitation" on the upload page.

**Comment by glandium** [comment]
FWIW, 50MB is too small for my use-case, OTOH, it's too big for diffoscope to handle reasonably on a server (see Debian bug 807997)

**Comment by lamby** [comment]
```
% curl -I http://archive.mozilla.org/pub/firefox/try-builds/mh@glandium.org-93eecb52fcadc562b0f52cb22a8971770446a12e/try-linux64/firefox-45.0a1.en-US.linux-x86_64.tar.bz2 | grep Content-Length
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 56.0M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Content-Length: 58721844
```

Bumping to 60mb.. ;)
