### ISSUE TITLE
State diffoscope version

### ISSUE THREAD

**Issue by danielshahaf** [lamby/trydiffoscope#24]
Suggestion: have index.html state the version of diffoscope being used (and any optional features present or absent).

**Comment by lamby** [comment]
I decided against this at the time as the results pages are kept for a while. Thus, looking at the homepage could be misleading. The results pages include the version used:

![](http://i.imgur.com/ZctZ82P.jpg)

**Comment by danielshahaf** [comment]
My rationale was wanting to know in advance whether it'd be quicker to upload a couple of .deb's or to download diffoscope + dependencies to a sid VM.  To make that decision it'd have been useful to know ahead of time what version would be used.

(Just stating that for posterity; not trying to argue for a revisitation of the decision.)

Thanks for the prompt answer.

**Comment by lamby** [comment]
> it'd be quicker to upload a couple of .deb's or to download diffoscope + dependencies to a sid VM.

As trydiffoscope updates every 24h, unless you do happen to hit that window where it has not updated to the latest version in sid, it's always using the latest version in sid :)

… and using trydiffoscope will likely be quicker than installing all the dependencies to a fresh VM!
