### ISSUE TITLE
FOOTER added after </html> tag

### ISSUE THREAD

**Issue by emanuelb** [lamby/trydiffoscope#27]
in:
https://github.com/lamby/trydiffoscope/blob/b0ff4956056addcdaf6dd9a2fa3b5471d43b5b69/trydiffoscope/compare/tasks.py#L14-L22
https://github.com/lamby/trydiffoscope/blob/b0ff4956056addcdaf6dd9a2fa3b5471d43b5b69/trydiffoscope/compare/tasks.py#L55-L60

result:
```
<div class="footer">Generated by <a href="https://diffoscope.org" target="_blank">diffoscope</a> 63</div>
</body>
</html>


<div class="footer">
  <p style="float: left;"><a href="****.txt">View text version</a></p>
  <p style="float: right; text-align: right; line-height: 24px;">
    Hosting provided by<br>
    <a href="http://anonym.to/?https://www.bytemark.co.uk"><img src="/static/images/bytemark.0eba90f2ad2d.png"></a>
  </p>
</div>
```

fix:
Add the footer before \</body> tag.

**Comment by lamby** [comment]
This is somewhat deliberate to avoid reading the file in.  What problems does this actually cause?

**Comment by emanuelb** [comment]
it cause errors in W3 HTML checker:
https://validator.w3.org/nu/?doc=https%3A%2F%2Ftry.diffoscope.org%2Fvcgdtctxartu.html
```
Error: Stray start tag div.
Fatal Error: Cannot recover after last error. Any further errors will be ignored.
```
