### ISSUE TITLE
Add options for diff results storing

### ISSUE THREAD

**Issue by emanuelb** [lamby/trydiffoscope#28]
Regarding storing:
1. Don't store the diff (result returned in response, no URL to fetch it again)
2. Store for X days/etc..
3. Store forever

Regarding public diffs:
1. add option for public diffs (the user can choose that diff result will be public), develop a page that show latest submissions

**Comment by lamby** [comment]
After some thought I'm going to wontfix this; I'm not seeing really any specific demand for this and somehow not storing the diff would actually not be straightforward. Anyone really *really* interested in security can simply run diffoscope locally, after all. Storing results forever (huge files!) isn't really going to be an option either, alas. :(

**Comment by emanuelb** [comment]
There is a comment now on homepage:
> Results are purged after 30 days

which mean option 2 is default with hardcoded days, can you add information in HTML diff page (such as:
https://try.diffoscope.org/vcgdtctxartu.html)
on how many days left until the diff is removed (" file will be removed in X days / file will be removed at date")

**Comment by lamby** [comment]
^
