### ISSUE TITLE
Support file uploads via URLs/Cloud storage

### ISSUE THREAD

**Issue by emanuelb** [lamby/trydiffoscope#29]
Currently it's possible to upload file only via file upload dialog (or drag & drop)
consider adding more options, such as:
1. using URLs (2 input fields, that receive URL)
2. integration with cloud providers (Google drive / DropBox / etc..)
Probably there are libraries that support both operations, for example:
https://netresearch.github.io/assetpicker/ (for integration with cloud providers)

**Comment by lamby** [comment]
> it's possible to upload file only via file upload dialog (or drag & drop)

Well, there is the command-line API :)

I'm going to go-ahead and wontfix this alas unless many more people would like this. Uploading files from Google Drive seems really rather an esoteric usecase to cater for.

**Comment by emanuelb** [comment]
what about the URLs case, such that following will be possible:
https://try.diffoscope.org/diff?URL1=https://website.com/version1.zip&URL2=https://website.com/version2.zip
which will download both files & show the diff between them.

**Comment by lamby** [comment]
If others are interested in that usecase I can dedicate some time to it but given that it would have to be well locked down (arbitrary URLs), I struggle to think that the intersection of folks who could use this feature and want to use trydiffoscope which — afer all — is for *trying* diffoscope :)
