### ISSUE TITLE
Detection of diffoscope related bugs (failed/missing comparators,etc..)

### ISSUE THREAD

**Issue by emanuelb** [lamby/trydiffoscope#34]
Diffoscope results can be analyzed in order to detect bugs in diffoscope which can improve it's development.

examples:
1. looking for ✂ in HTML output, may bring more file-formats that need beautifier, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836786
2. looking for comments:
> No file format specific differences found inside, yet data differs

> stderr from

may bring failed comparators / bugs in comparators.

3. looking for binary comparison (no comparator used) can bring attention to unsupported file-formats.

I am working on tool that will analyze diffoscope output (for detection of reproducibility issues) in github repo at:
https://github.com/emanuelb/RID
which currently support detection of above examples (it transform HTML output to XML, which parsed for issues that added to SQLITE db file, SQL queries can be used to return information about each issue-type)

This issue is about:
1. Adding note about the usage of analytics in order to improve diffoscope to website in Terms of Service if used, maybe ask the user if he agree to share the diff with developers (in case his diff results yield errors)
2. Add such analytics when diffoscope support output XML format.

Thoughts?

**Comment by lamby** [comment]
Did you mean to post this here? :) I don't think this is something for trydiffoscope?

**Comment by emanuelb** [comment]
Yes, gathering information about potential diffoscope issues/bugs from many diffoscope outputs is very useful, which can happen in services like trydiffoscope / tests.reproducible-builds.org.

**Comment by lamby** [comment]
I love the idea, I just think it would be more sensible to add to t.r-b.org. trydiffoscope is really just meant as a "demo" of diffoscope rather than a service we should use to categorise issues, etc.etc.
